### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by sluzhynskyi** [idlesign/keybind#3]
Python 3.7 windows 10. error when I run example, pls fix.

**Comment by idlesign** [comment]
Have you read the [README](https://github.com/idlesign/keybind/blob/master/README.rst)?
Please take a note: **Requires X11 (X Window System). For UNIX-like systems, e.g. Linux.**

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
